# permissions for end users to edit solacerdps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solacerdp-editor-role
rules:
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacerdps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacerdps/status
  verbs:
  - get
