# permissions for end users to view solacequeues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solacequeue-viewer-role
rules:
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacequeues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacequeues/status
  verbs:
  - get
