# permissions for end users to edit solacequeues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solacequeue-editor-role
rules:
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacequeues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solace.lmbrn.ca
  resources:
  - solacequeues/status
  verbs:
  - get
