apiVersion: solace.lmbrn.ca/v1alpha1
kind: SolaceQueue
metadata:
  name: test-queue-1
spec:
  topicSubscriptions:
    - test/topic1
    - test/topic2
---
apiVersion: solace.lmbrn.ca/v1alpha1
kind: SolaceQueue
metadata:
  name: test-queue-2
spec:
  accessType: non-exclusive
  topicSubscriptions:
    - test/topic3
    - test/topic4
---
apiVersion: solace.lmbrn.ca/v1alpha1
kind: SolaceRdp
metadata:
  name: test-rdp
spec:
  consumers:
    - host: webhook.site
      tlsEnabled: true
  queueBindings:
    - queueName: test-queue-1
      postRequestTarget: /d078c134-0dcc-497a-ae54-644d16d6e8fe
    - queueName: test-queue-2
      postRequestTarget: /d078c134-0dcc-497a-ae54-644d16d6e8fe