// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceQueue) DeepCopyInto(out *SolaceQueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceQueue.
func (in *SolaceQueue) DeepCopy() *SolaceQueue {
	if in == nil {
		return nil
	}
	out := new(SolaceQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolaceQueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceQueueList) DeepCopyInto(out *SolaceQueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SolaceQueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceQueueList.
func (in *SolaceQueueList) DeepCopy() *SolaceQueueList {
	if in == nil {
		return nil
	}
	out := new(SolaceQueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolaceQueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceQueueSpec) DeepCopyInto(out *SolaceQueueSpec) {
	*out = *in
	if in.TopicSubscriptions != nil {
		in, out := &in.TopicSubscriptions, &out.TopicSubscriptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceQueueSpec.
func (in *SolaceQueueSpec) DeepCopy() *SolaceQueueSpec {
	if in == nil {
		return nil
	}
	out := new(SolaceQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceQueueStatus) DeepCopyInto(out *SolaceQueueStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceQueueStatus.
func (in *SolaceQueueStatus) DeepCopy() *SolaceQueueStatus {
	if in == nil {
		return nil
	}
	out := new(SolaceQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdp) DeepCopyInto(out *SolaceRdp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdp.
func (in *SolaceRdp) DeepCopy() *SolaceRdp {
	if in == nil {
		return nil
	}
	out := new(SolaceRdp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolaceRdp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdpConsumer) DeepCopyInto(out *SolaceRdpConsumer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdpConsumer.
func (in *SolaceRdpConsumer) DeepCopy() *SolaceRdpConsumer {
	if in == nil {
		return nil
	}
	out := new(SolaceRdpConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdpList) DeepCopyInto(out *SolaceRdpList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SolaceRdp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdpList.
func (in *SolaceRdpList) DeepCopy() *SolaceRdpList {
	if in == nil {
		return nil
	}
	out := new(SolaceRdpList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolaceRdpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdpQueueBinding) DeepCopyInto(out *SolaceRdpQueueBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdpQueueBinding.
func (in *SolaceRdpQueueBinding) DeepCopy() *SolaceRdpQueueBinding {
	if in == nil {
		return nil
	}
	out := new(SolaceRdpQueueBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdpSpec) DeepCopyInto(out *SolaceRdpSpec) {
	*out = *in
	if in.Consumers != nil {
		in, out := &in.Consumers, &out.Consumers
		*out = make([]SolaceRdpConsumer, len(*in))
		copy(*out, *in)
	}
	if in.QueueBindings != nil {
		in, out := &in.QueueBindings, &out.QueueBindings
		*out = make([]SolaceRdpQueueBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdpSpec.
func (in *SolaceRdpSpec) DeepCopy() *SolaceRdpSpec {
	if in == nil {
		return nil
	}
	out := new(SolaceRdpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolaceRdpStatus) DeepCopyInto(out *SolaceRdpStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolaceRdpStatus.
func (in *SolaceRdpStatus) DeepCopy() *SolaceRdpStatus {
	if in == nil {
		return nil
	}
	out := new(SolaceRdpStatus)
	in.DeepCopyInto(out)
	return out
}
