apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solace-operator.fullname" . }}
  labels:
    {{- include "solace-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "solace-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "solace-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "solace-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SEMP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "solace-operator.fullname" . }}
                  key: sempUrl
            - name: SEMP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "solace-operator.fullname" . }}
                  key: username
            - name: SEMP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "solace-operator.fullname" . }}
                  key: password
            - name: SEMP_MSGVPN
              valueFrom:
                secretKeyRef:
                  name: {{ template "solace-operator.fullname" . }}
                  key: messageVpn
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
