apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "solace-operator.fullname" . }}
  labels:
    {{- include "solace-operator.labels" . | nindent 4 }}
data:
  sempUrl: "{{ .Values.solaceBroker.sempUrl | b64enc }}"
  useraname: "{{ .Values.solaceBroker.username | b64enc }}"
  password: "{{ .Values.solaceBroker.password | b64enc }}"
  messageVpn: "{{ .Values.solaceBroker.messageVpn | b64enc }}"